set shell := ["bash", "-euo", "pipefail", "-c"]

import '../../../.build/just/lib.just'
import? "~/.config/just/lib/std.just"

dotdir := shell("yq '.dotdir' data.yml | envsubst")
user := `whoami`
dot_docker := xdg_config + "/docker"

fetch:
    curl "https://just.arusty.dev/lib/std.just" > "{{dotdir}}/lib/std.just"
    curl "https://just.arusty.dev/global/{{ user }}.just" > "{{dotdir}}/justfile"

install: mktree
    ln -sf "{{justfile_directory()}}/justfile" "{{dotdir}}/justfile"

# Deploy docker config for profile (DOCKER_WORKSPACE targets application)
docker-deploy profile="core":
    just -f "{{ dot_docker }}/justfile" deploy "{{ profile }}"

# Build docker images for profile (DOCKER_WORKSPACE targets application)
docker-build profile="core":
    just -f "{{ dot_docker }}/justfile" build "{{ profile }}"

# Destroy docker config for profile (DOCKER_WORKSPACE targets application)
docker-destroy profile="core":
    just -f "{{ dot_docker }}/justfile" destroy "{{ profile }}"

# List docker resources of kind (profiles, containers[labels...], projects)
docker-ls kind="projects" *args:
    just -f "{{ dot_docker }}/justfile" "list-docker-{{ kind }}" {{ args }}

# Create certificates & DNS records
init-docker:
    just -f "{{ dot_docker }}/justfile" init

mktree:
    mkdir -p "{{ xdg_data_home }}/just"
    mkdir -p "{{ xdg_config_home }}/just/lib"
    mkdir -p "{{ xdg_cache_home }}/just"
    mkdir -p "{{ xdg_state_home }}/just"

reboot-network:
    warp-cli disconnect
    warp-cli connect
    sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
    networksetup -setairportpower en0 off && sleep 2 && networksetup -setairportpower en0 on
    sudo ipconfig set en0 DHCP
