set shell := ["bash", "-euo", "pipefail", "-c"]

import '../.build/just/lib.just'

[parallel]
install:
    just -f meilisearch/justfile install
    just -f qdrant/justfile install
    just -f surrealdb/justfile install
