---
vars:
  SHELLS:
    - bash
    - zsh
    - fish
  CACHE: ".local/cache"
  PKGS: ".local/pkg"
  CFG: ".config"
  LIBS: ".local/lib"
  DATA: ".local/data"
  STATE: ".local/state"
  GRPCTR: "Group Containers"
path:
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - $HOME/.nix-profile/bin
  - /nix/var/nix/profiles/default/bin
  - /usr/local/bin
  - /System/Cryptexes/App/usr/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  - $HOME/.cargo/bin
  - $HOME/.volta/bin
  - /Applications/Ghostty.app/Contents/MacOS
  - $HOME/.orbstack/bin
paths:
  - env: STARSHIP_CONFIG
    path: $HOME/$CFG/starship.toml
    type: file
    tags:
      - starship
      - dots
  - env: ANSIBLE_CONFIG
    path: $HOME/$CFG/ansible/config.ini
    type: file
    tags:
      - dots
      - ansible
  - env: HOME_CACHE
    path: "$HOME/$CACHE"
    type: dir
    tags:
      - dots
  - env: HOME_CONFIG
    path: $HOME/$CFG
    type: dir
    tags:
      - dots
  - env: HOME_DATA
    path: $HOME/$DATA
    type: dir
    tags:
      - dots
  - env: HOME_PKG
    path: $HOME/$PKGS
    type: dir
    tags:
      - dots
  - env: HOME_LIB
    path: $HOME/$LIBS
    type: dir
    tags:
      - dots
  - env: HISTFILE
    path: "$HOME/$CACHE/zsh/history"
    type: file
    tags:
      - zsh
      - history
  - env: SHELL_SESSION_DIR
    path: $HOME/$CACHE/zsh/sessions
    type: dir
    tags:
      - zsh
  - env: ZCOMPDUMP
    path: $HOME/$CACHE/zsh/compdump
    type: dir
    tags:
      - zsh
  - env: ZDOTDIR
    path: $HOME/$CFG/zsh
    type: dir
  - env: ANTIDOTE_HOME
    path: $ZDOTDIR/plugins
    type: dir
  - env: ZFUNCS
    path: $ZDOTDIR/functions
    type: dir
  - env: ZPLUGINS
    path: $ZDOTDIR/plugins
    type: dir
  - env: ZCOMPLETE
    path: $ZDOTDIR/completions
    type: dir
  - env: ZENV
    path: $ZDOTDIR/.zshenv
    type: file
  - env: ZSH_EVALCACHE_DIR
    path: $HOME/$CACHE/zsh/evalcache
    type: dir
  - env: SSH_AUTH_SOCK
    path: $HOME/Library/$GRPCTR/2BUA8C4S2C.com.1password/t/agent.sock
    type: env
  - env: MANPATH
    path: /usr/local/man:$MANPATH
    type: env
  - env: LANG
    path: en_US.UTF-8
    type: env
  - env: HIST_STAMPS
    path: mm/dd/yyyy
    type: env
  - env: HISTSIZE
    path: "10000"
    type: env
  - env: SAVEHIST
    path: "10000"
    type: env
  - env: ZSH_DISABLE_COMPFIX
    path: "true"
    type: env
  - env: _ZO_DATA_DIR
    path: $HOME/$DATA/zoxide
    type: dir
