set shell := ["bash", "-euo", "pipefail", "-c"]

import '../.build/just/lib.just'

dotdir := shell("yq '.dotdir' data.yml | envsubst")

install: config

config: mktree
    ln -sf "{{justfile_directory()}}/config.toml" "{{dotdir}}/aerospace.toml"
    rm -f "$HOME/.aerospace.toml"

mktree:
    mkdir -p "{{dotdir}}"
