xdg_config := env("XDG_CONFIG_HOME", env("HOME") + "/.config")
mcp_root := env("HOME") + "/repos" + "/mcp"
dot_mcp := root + "/.ai/mcp"
root := `git rev-parse --show-toplevel`
claude_desktop_config := env("HOME") + "/Library/Application Support/Claude/claude_desktop_config.json"
claude_code_global_config := env("HOME") + "/.claude/settings.json"
claude_code_project_config := root + "/.claude/settings.json"
zed_global_config := env("HOME") + "/.config/zed/settings.json"
zed_project_config := root + "/.zed/settings.json"
free_cad_mods_dir := env("HOME") + "/Library/Preferences/FreeCAD/Mod"

# JQ Queries

mcp_env_string := '[$json | .env | to_entries[] | "--env \(.value)"] | join(" ")'
mcp_arg_string := '$json | .args | join(" ")'
transport_type := '$json | .type'
transport_url := '$json | .url'
mcp_command := '$json | .command'
transport := '$json | .transport'
gemini := '. | $key | .repo'
mcp := '. | $key | del(.transport) | del(.repo)'

config-all-ai-tools mcptool: (claude-desktop mcptool) (zed mcptool) (claude-code mcptool)

hydrate file:
    #!/usr/bin/env bash
    json=$(yq --output-format json '.' "{{ dot_mcp }}/{{ file }}")
    injected=$(echo "$json" | op inject)
    export MCP_ROOT="{{ mcp_root }}"
    output=$(echo "$injected" | envsubst)
    echo "$output"

zed key scope="global":
    #!/usr/bin/env bash
    cfg="{{ if scope == 'global' { zed_global_config } else { zed_project_config } }}" # Pick Config File
    json=$(just hydrate "mcp.yaml" | jq --arg key "{{ key }}" '{{ mcp }}') # Extract Map from YAML
    mcp_json="{\"{{ key }}\": $json}" # JSON Object to add to Zed Config
    clean_zed_config=$(sed -e '\|^[[:space:]]*//.*$|d' -e 's|//.*||g' "$cfg") # Clean Config
    jq -n --argjson mcp "$mcp_json" --argjson cfg "$clean_zed_config" '$cfg | .context_servers += $mcp' "$cfg" | sponge "$cfg"

claude-desktop key:
    #!/usr/bin/env bash
    raw="$(just hydrate "mcp.yaml")"
    # foo=$(jq -n --arg key "{{ key }}" --argjson json "$raw" '$json | to_entries[] | select(.key == $key) | .value | del(.transport) | del(.repo)')
    json=$(jq -r -n --arg key "{{ key }}" --argjson json "$raw" '$json | to_entries[] | select(.key == $key) | .value | del(.transport) | del(.repo) | if (. | keys != []) then { {{ key }}: .} else "null" end')
    if [[ "$json" != "null" ]]; then
        jq --argjson mcp "$json" '.mcpServers += $mcp' "{{ claude_desktop_config }}" | sponge "{{ claude_desktop_config }}"
    fi

docker-mcp-toolkit key:
    docker mcp secret set GITHUB.PERSONAL_ACCESS_TOKEN=op://developer/github/docker-mcp-toolkit/token
    echo "TODO"

claude-code key:
    #!/usr/bin/env bash
    raw="$(just hydrate "mcp.yaml")"
    json="$(jq -n --arg key "{{ key }}" --argjson json "$raw" '$json | to_entries[] | select(.key == $key) | .value')"
    transport="$(jq -n --argjson json "$json" '$json | if .transport != null then .transport else "null" end')"
    if [[ "$transport" != "null" ]]; then
        method="$(jq -r -n --argjson json "$transport" '{{ transport_type }}')"
        if [[ "$method" == "stdio" ]]; then
            envs="$(jq -n --argjson json "$json" '{{ mcp_env_string }}')"
            args="$(jq -n --argjson json "$json" '{{ mcp_arg_string }}')"
            cmd="$(jq -n --argjson json "$json" '{{ mcp_command }}')"
            claude mcp add --transport stdio "{{ key }}" $envs -- $cmd $args
        elif [[ "$method" == "http" || "$method" == "sse" ]]; then
            url=$(jq -r -n --argjson json "$transport" '$json | .url')
            claude mcp add --transport $method "{{ key }}" "$url"
        else
            echo "Method not supported"
        fi
    else
        echo "Transport not specified"
    fi

gemini-cli key:
    #!/usr/bin/env bash
    json=$(just hydrate "mcp.yaml" | jq '{{ gemini }}')
    gemini extensions install https://github.com/huggingface/hf-mcp-server

claud-hook key scope="global":
    #!/usr/bin/env bash
    cfg="{{ if scope == 'global' { claude_code_global_config } else { claude_code_project_config } }}" # Pick Config File
    json=$(just hydrate "mcp.yaml" | jq --arg key "{{ key }}" '{{ mcp }}') # Extract Map from YAML
    claude mcp add --transport http hugging-face https://huggingface.co/mcp

kicad: (config-all-ai-tools "kicad")
    #!/usr/bin/env bash
    brew install uv
    cd "{{ mcp_root }}"
    # git clone https://github.com/lamaalrajih/kicad-mcp.git
    cd kicad-mcp
    # Install dependencies – `uv` will create a `.venv/` folder automatically
    # (Install `uv` first: `brew install uv` on macOS or `pipx install uv`)
    make install
    # Optional: activate the environment for manual commands
    source .venv/bin/activate
    # Edit the .env file
    echo "" > .env
    # Add paths to your KiCad projects (comma-separated)
    echo "KICAD_APP_PATH=/Applications/KiCad/KiCad.app" >> .env
    echo "KICAD_SEARCH_PATHS=~/repos/hardware" >> .env
    echo "KICAD_USER_DIR=~/Documents/KiCad" >> .env
    # python main.py

kicad-alt:
    #!/usr/bin/env bash
    # Install Node.js
    brew install node@20
    # Clone and build
    cd "{{ dot_mcp }}"
    git clone https://github.com/mixelpixx/KiCAD-MCP-Server.git "kicad-mcp-alt"
    cd KiCAD-MCP-Server
    npm install
    pip3 install -r requirements.txt
    npm run build

surrealdb:
    #!/usr/bin/env bash
    echo "TODO"

docling: (pyenv "3.12" "docling")
    #!/usr/bin/env bash
    brew install tesseract leptonica pkg-config
    cd "{{ mcp_root }}/docling"
    python3 -m pip install --upgrade pip
    python3 -m pip install "docling[asr,vlm,easyocr,tesserocr,ocrmac,rapidocr]" --extra-index-url https://download.pytorch.org/whl/cpu
    just config-all-ai-tools "docling"

pyenv ver local:
    #!/usr/bin/env bash
    brew install pyenv
    if ![[ pyenv "local" | grep -o "{{ ver }}" ]]; then
        mkdir -p "{{ mcp_root }}/docling"
        cd "{{ mcp_root }}/{{ local }}"
        pyenv install "{{ ver }}"
        pyenv local "{{ ver }}"
    fi

freecad:
    #!/usr/bin/env bash
    brew install freecad
    mkdir -p "{{ free_cad_mods_dir }}"
    cd "{{ free_cad_mods_dir }}"
    git clone https://github.com/bonninr/freecad_mcp.git "freecad-mcp"

gitlab-ci-local:
    #!/usr/bin/env bash
    volta install gitlab-ci-local
    echo "TODO"

github:
    #!/usr/bin/env bash
    echo "TODO"

gitlab:
    #!/usr/bin/env bash
    echo "TODO"

gitea:
    #!/usr/bin/env bash
    echo "TODO"

bitbucket:
    #!/usr/bin/env bash
    echo "TODO"

jira: (claude-desktop "jira") (zed "jira") (claude-code "jira")
    #!/usr/bin/env bash
    echo "TODO"

confluence:
    #!/usr/bin/env bash
    echo "TODO"

node:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/workbackai/mcp-nodejs-debugger

cloudflare:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/cloudflare/mcp-server-cloudflare

css:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/stolinski/css-mcp

mongo:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/mongodb-js/mongodb-mcp-server

claude-gemini:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/BeehiveInnovations/gemini-mcp-server

unity:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/justinpbarnett/unity-mcp

playwright:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/microsoft/playwright-mcp

fastapi:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/tiangolo/fastapi
    # https://github.com/tadata-org/fastapi_mcp

task-master:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/eyaltoledano/claude-task-master

apple-notes:
    #!/usr/bin/env bash
    echo "TODO"
    # https://github.com/krasun/notes-mcp

apple: apple-notes
    #!/usr/bin/env bash
    echo "TODO"

sketch:
    #!/usr/bin/env bash
    if [ -d /Applications/Sketch.app ]; then
        # defaults write com.bohemiancoding.sketch3 mcpServerPortNumber -int 31126
        just claude-code sketch
        just claude-desktop sketch
        # docker mcp server enable sketch
    else
        echo "Sketch.app not found"
    fi
    # https://github.com/justinpbarnett/sketch-mcp

docker:
    #!/usr/bin/env bash
    echo "TODO"
    docker mcp secret set GITHUB.PERSONAL_ACCESS_TOKEN=github_pat_YOUR_TOKEN_HERE
