set shell := ["bash", "-euo", "pipefail", "-c"]

import '../.build/just/lib.just'

dotdir := shell("yq '.dotdir' data.yml | envsubst")

install: config configs themes

mktree:
    mkdir -p "{{dotdir}}"

config: mktree
    ln -sf "{{justfile_directory()}}/config" "{{dotdir}}/config"

configs: mktree
    ln -sf "{{justfile_directory()}}/configs" "{{dotdir}}/configs"

themes: mktree
    ln -sf "{{justfile_directory()}}/themes" "{{dotdir}}/themes"
