import '../.build/just/lib.just'
set shell := ["zsh", "-cu"]

dot := xdg_config + "/git"

install:
    @mkdir -p "{{ dot }}"/{templates,configs,bin}
    @for config in `ls ./configs/`; do \
        cat configs/$config | envsubst | op inject -f -o "{{ dot }}/configs/$config"; \
    done
    @cat config | envsubst | op inject -f -o "{{ dot }}/config"
    @cp -r templates/* "{{ dot }}/templates"
    @cp -r bin/* "{{ dot }}/bin"

mktree:
    @mkdir -p "{{ dot }}"/{templates,configs,bin}
