set shell := ["bash", "-euo", "pipefail", "-c"]

import '../../.build/just/lib.just'

dotdir := shell("yq '.dotdir' data.yml | envsubst")

test:
    echo "Testing ZSH"
    docker run --rm -it --device /dev/kvm -v /tmp/.X11-unix:/tmp/.X11-unix zshrc:latest
    echo "Testing Complete"

install: config dot_helper
    @echo " ::: source {{dotdir}}/.zshenv"
    @echo " ::: source {{dotdir}}/.zshrc"

config: mktree
    ln -sf "{{justfile_directory()}}/.zshenv" "{{dotdir}}/.zshenv"
    ln -sf "{{justfile_directory()}}/.zshrc" "{{dotdir}}/.zshrc"
    ln -sf "{{justfile_directory()}}/.zprofile" "{{dotdir}}/.zprofile"
    ln -sf "{{justfile_directory()}}/.zlogin" "{{dotdir}}/.zlogin"
    ln -sf "{{justfile_directory()}}/plugins" "{{dotdir}}/plugins"
    ln -sf "{{justfile_directory()}}/init" "{{dotdir}}/init"
    ln -sf "{{justfile_directory()}}/functions" "{{dotdir}}/functions"
    ln -sf "{{justfile_directory()}}/completions" "{{dotdir}}/completions"

# System file - copy required (symlinks not reliable for /etc)
etc-zshenv:
    sudo cp "{{justfile_directory()}}/etc/.zshenv" /etc/zshenv

dot_helper:
    ln -sf "{{justfile_directory()}}/../dot_helper" "{{xdg_config}}/dot_helper"

mktree:
    mkdir -p "{{dotdir}}"
