---
- domain: com.apple.dock
  key: "autohide"
  type: bool
  value: "true"
  kill: Dock
- domain: com.apple.dock
  key: "autohide-delay"
  type: float
  value: "0.1"
  kill: Dock
- domain: com.apple.dock
  key: "tilesize"
  type: int
  value: "36"
  kill: Dock
- domain: com.apple.dock
  key: "show-recents"
  type: bool
  value: "false"
  kill: Dock
- domain: com.apple.screencapture
  key: "location"
  type: string
  value: "~/Pictures"
  kill: SystemUIServer
- domain: NSGlobalDomain
  key: "AppleShowAllExtensions"
  type: bool
  value: "false"
  kill: Finder
- domain: com.apple.finder
  key: "AppleShowAllFiles"
  type: bool
  value: "false"
  kill: Finder
- domain: com.apple.finder
  key: "ShowPathbar"
  type: bool
  value: "true"
  kill: Finder
- domain: com.apple.finder
  key: "FXPreferredViewStyle"
  type: string
  value: "clmv"
  kill: Finder
- domain: com.apple.finder
  key: "_FXSortFoldersFirst"
  type: bool
  value: "true"
  kill: Finder
- domain: com.apple.finder
  key: "FXDefaultSearchScope"
  type: string
  value: "SCcf"
  kill: Finder
- domain: com.apple.finder
  key: "FXRemoveOldTrashItems"
  type: bool
  value: "true"
  kill: Finder
- domain: NSGlobalDomain
  key: "NSDocumentSaveNewDocumentsToCloud"
  type: bool
  value: "false"
  kill: null
- domain: NSGlobalDomain
  key: com.apple.mouse.linear
  type: bool
  value: "false"
  kill: null
- domain: NSGlobalDomain
  key: com.apple.mouse.scaling
  type: float
  value: "1"
  kill: null
- domain: NSGlobalDomain
  key: AppleKeyboardUIMode
  type: int
  value: "2"
  kill: null
