set unstable

cache := env("HOME") + "/.local/cache"
brew := which("brew")

install:
    @mkdir -p "{{cache}}/cron"
    @echo "{'cache': '{{cache}}', 'brew':'{{brew}}'}" | mustache templates/brew.mustache | envsubst > just.cron
    @crontab just.cron
