nix = "0.30.1"
# crontab
# symlink-rs
# symlink = "0.1.0"
# std::os::unix::fs
# std::os::windows::fs
# gitoxide
#
#
# forge-rs = "0.5.1"
# mksls = "2.0.0"
# dotf = "0.2.2"
# check-symlinks = "0.4.0"
#
# homebrew = "0.2.6"
# brew = "0.2.0"
# cargo-brew = "0.1.4"
#
