install:
    mv *.just {{ xdg_data }}/just/
    mv main.justfile {{ xdg_config }}/just/justfile

mktree:
    mkdir -p {{ xdg_data }}/just
    mkdir -p {{ xdg_config }}/just
    mkdir -p {{ xdg_cache }}/just
    mkdir -p {{ xdg_state }}/just
    mkdir -p {{ xdg_bin }}
