import '../.build/just/lib.just'

sponge := require("sponge")

jq := jqd + "/homebrew"
homebrew := root + "/homebrew"
manifest := homebrew + "/install.json"

clean:
    jq -f {{jq}}/lint.jq {{manifest}} | {{sponge}} {{manifest}} && just commit {{manifest}} "chore(homebrew): updated homebrew manifest"

commit target msg:
    @git stash
    @git add {{homebrew}}/{{target}}
    @git commit -S -m "{{msg}}" || echo "No changes to commit"
    @git stash apply
