set shell := ["bash", "-euo", "pipefail", "-c"]
set unstable

import '../../.build/just/lib.just'

cache := env("HOME") + "/.local/cache"
brew := which("brew")

install:
    @mkdir -p "{{cache}}/cron"
    @echo "{'cache': '{{cache}}', 'brew':'{{brew}}'}" | mustache templates/brew.mustache | envsubst > just.cron
    @crontab just.cron

clean:
    rm *.cron
