# Credential Configuration
# Manages authentication credentials for remote repositories

[credential]
# Credential helper to use for storing passwords
helper = "cache --timeout=3600"  # Cache for 1 hour

# Use path as part of the credential context
useHttpPath = false

# Default username when not specified in URL
username = "default-username"

# Per-URL credential settings using dot notation
[credential."https://example.com"]
username = "specific-username"
helper = "store"

[credential."https://github.com"]
helper = ""  # Clear any previous helpers
helper = "!/usr/bin/gh auth git-credential"  # Use GitHub CLI

[credential."https://gitlab.com"]
helper = "cache --timeout=7200"  # Cache for 2 hours
username = "gitlab-user"

[credential."https://bitbucket.org"]
helper = "osxkeychain"  # Use macOS keychain
username = "bitbucket-user"

[credential."https://dev.azure.com"]
helper = "manager-core"  # Git Credential Manager Core

# Corporate/Enterprise examples
[credential."https://git.company.com"]
helper = "cache --timeout=28800"  # Cache for 8 hours
username = "corporate-username"
# Can also specify provider for Git Credential Manager
provider = "generic"

[credential."ssh://git@git.company.com"]
# SSH URLs typically don't use credential helpers
# but username can still be specified
username = "git"

# Common credential helpers:
# - cache: Cache credentials in memory for a period
#   Options: --timeout=<seconds> (default 900)
#   Example: "cache --timeout=3600"
#
# - store: Store credentials in plain text file
#   Options: --file=<path> (default ~/.git-credentials)
#   Example: "store --file ~/.my-credentials"
#
# - osxkeychain: macOS Keychain Access
#   No options needed
#
# - wincred: Windows Credential Manager (deprecated)
#   Use manager-core instead
#
# - manager-core: Git Credential Manager Core
#   Cross-platform, supports many providers
#   Options: various provider-specific options
#
# - manager: Git Credential Manager (older version)
#   Being replaced by manager-core
#
# - libsecret: Linux Secret Service API
#   For GNOME Keyring, KWallet, etc.
#
# - gnome-keyring: GNOME Keyring (deprecated)
#   Use libsecret instead

# Custom credential helper example
# helper = "!f() { test \"$1\" = get && echo \"password=$(pass $2)\"; }; f"

# Multiple helpers can be specified
# They are tried in order until one succeeds
# [credential]
# helper = "osxkeychain"
# helper = "store --file ~/.backup-credentials"

# Notes:
# - Use empty string to clear inherited helpers: helper = ""
# - Helpers starting with ! are treated as shell commands
# - URL matching is done from most to least specific
# - useHttpPath=true makes paths part of credential context
#   (useful for different repos on same host)