import '../.build/just/lib.just'

cue := root + "/.build/cue"
template_index := root + "/.data/indexs/templates.json"

# Syncs schema for .meta/schema.json -> */.meta.json
install:
    #!/usr/bin/env bash
    echo "Installing .meta.json schemas"
    fd -t d ".*" --full-path {{root}} | while read -r i; do
        if [[ -f "${i}.meta.json" ]]; then
            cat $i/.meta.json \
           | jq -s \
            --arg path "$(echo $i | sed 's|{{root}}/||')" \
            ' .[] += { "path": "\($path)" } ' {{root}}/.meta/schema.json > $i/.meta.json
        else
            jq \
            --arg id "$(uuidgen)" \
            --arg path "$(echo $i | sed 's|{{root}}/||')" \
            ' .[] += { "id": "\($id)", "path": "\($path)" }' {{root}}/.meta/schema.json > $i/.meta.json
        fi
    done

validate:
    #!/usr/bin/env bash
    fd -t f --hidden "meta" -e json --full-path {{root}} | while read -r i; do
        if [[ -f "${i}" ]]; then
            cue vet -c {{datad}}/schema.cue ${i}
        else
        fi
    done

get-completions:
    jq -s 'add | .[] | select(.completions != null and .completions != false)' **/.meta.json

get-aliases:
    jq -s 'add | .[] | select(.aliases != null and .aliases != false)' **/.meta.json

get-paths:
    jq -s 'add | .[] | select(.paths != null and .paths != false)' **/.meta.json

get-functions:
    jq -s 'add | .[] | select(.functions != null and .functions != false)' **/.meta.json

get-configs:
    echo ""

update-index:
    jq -s 'add | .[] | select(.functions != null and .functions != false)' **/.meta.json

get-todo:
    jq -s 'add | ' **/.meta.json

# Add a unique reference to a template
add-template path:
    echo "Adding template..."
    cat {{template_index}} | jq --arg id "$(uuidgen)" '(. + {id: "$id", path: "{{path}}"}) | unique_by(.id)' > {{template_index}}

# Add a unique reference to a dependency
add-dependency path:
    echo "Adding template..."
    kuzu example.kuzu
    cat {{template_index}} | jq --arg id "$(uuidgen)" '(. + {id: "$id", path: "{{path}}"}) | unique_by(.id)' > {{template_index}}

# returns paths of all .meta.json files
get-all-meta:
    fd -t f -e json --hidden meta {{root}}
