set shell := ["bash", "-euo", "pipefail", "-c"]

import '../.build/just/lib.just'

dotdir := shell("yq '.dotdir' data.yml | envsubst")

install: config

config: mktree
    ln -sf "{{justfile_directory()}}/config.yml" "{{dotdir}}/config.yml"
    ln -sf "{{justfile_directory()}}/skin.yml" "{{dotdir}}/skin.yml"

mktree:
    mkdir -p "{{dotdir}}"
