tools:
  offsec:
    - github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    - github.com/projectdiscovery/cloudlist/cmd/cloudlist@latest
    - github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
    - github.com/projectdiscovery/katana/cmd/katana@latest
    - github.com/projectdiscovery/chaos-client/cmd/chaos@latest
    - github.com/projectdiscovery/uncover/cmd/uncover@latest
    - github.com/projectdiscovery/asnmap/cmd/asnmap@latest
    - github.com/projectdiscovery/alterx/cmd/alterx@latest
    - github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
    - github.com/projectdiscovery/httpx/cmd/httpx@latest
    - github.com/projectdiscovery/dnsx/cmd/dnsx@latest
    - github.com/projectdiscovery/tlsx/cmd/tlsx@latest
    - github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
    - github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest
    - github.com/projectdiscovery/cvemap/cmd/cvemap@latest
    - github.com/projectdiscovery/notify/cmd/notify@latest
    - github.com/projectdiscovery/pdtm/cmd/pdtm@latest
    - github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
    - github.com/projectdiscovery/cdncheck/cmd/cdncheck@latest
    - github.com/projectdiscovery/aix/cmd/aix@latest
    - github.com/projectdiscovery/proxify/cmd/proxify@latest
    - github.com/projectdiscovery/simplehttpserver/cmd/simplehttpserver@latest
  templating:
    - cuelang.org/go/cmd/cue@master
    - github.com/cbroglie/mustache/cmd/mustache@latest
templates:
  offsec:
    - https://github.com/projectdiscovery/nuclei-templates
