import '../.build/just/lib.just'

zsh := root + "/zsh"
docker := root + "/.build/zsh.Dockerfile"
dotdir := xdg_config + "/zsh/"

test:
    echo "Testing ZSH"
    docker run --rm -it --device /dev/kvm -v /tmp/.X11-unix:/tmp/.X11-unix zshrc:latest
    echo "Testing Complete"

install: zenv zrc zprofile zlogin zplugins zinit zcomp zfuncs dot_helper

zplugins: mktree
    @cp -r {{zsh}}/plugins "{{ dotdir }}"

zinit: mktree
    @cp -r {{zsh}}/init "{{ dotdir }}"

zfuncs: mktree
    @cp -r {{zsh}}/functions "{{ dotdir }}"

zcomp: mktree
    @cp -r {{zsh}}/completions "{{ dotdir }}"

dot_helper: mktree
    @cp -r {{root}}/dot_helper/ {{xdg_config}}

zlogin: mktree
    @cp {{zsh}}/.zlogin {{dotdir}}/.zlogin
    @echo "Copied .zlogin -> {{dotdir}}/.zlogin"

zprofile: mktree
    @cp {{zsh}}/.zprofile {{dotdir}}/.zprofile
    @echo "Copied .zprofile -> {{dotdir}}/.zprofile"

zrc: mktree
    @cp {{zsh}}/.zshrc {{dotdir}}/.zshrc
    @echo "Copied .zshrc -> {{dotdir}}/.zshrc"

zenv: mktree
    @cp {{zsh}}/.zshenv {{dotdir}}/.zshenv
    @echo "Copied .zshenv -> {{dotdir}}/.zshenv"

mktree:
    @mkdir -p "{{ dotdir }}"
