set shell := ["bash", "-euo", "pipefail", "-c"]

# AeroSpace tiling window manager
mod aerospace 'aerospace/justfile'
# Amethyst tiling window manager
mod amethyst 'amethyst/justfile'

install:
    #!/usr/bin/env bash
    for mod in aerospace amethyst; do
        echo "📦 wm:$mod"
        "{{ just_executable() }}" -f "{{ justfile_directory() }}/$mod/justfile" install
    done
