set shell := ["bash", "-euo", "pipefail", "-c"]

# Sketch design application
mod sketch 'sketch/justfile'
# GIMP image editor
mod gimp 'gimp/justfile'

install:
    #!/usr/bin/env bash
    for mod in sketch gimp; do
        echo "📦 design:$mod"
        "{{ just_executable() }}" -f "{{ justfile_directory() }}/$mod/justfile" install
    done
