---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation
APPLY_FIXES: all
EXCLUDED_DIRECTORIES:
  - .cache
  - megalinter-reports
  - site
  - pproxy
  - venv
  - node_modules
  - .vscode
  - .zed
  - .notes

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - CSS
  - EDITORCONFIG
  # - SPELL # Uncomment to disable checks of spelling mistakes
  - JAVASCRIPT
  - TEKTON
DISABLE_LINTERS:
  - JSON_PRETTIER
  - PYTHON_PYRIGHT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - SPELL_PROSELINT
  - SPELL_MISSPELL
  - SPELL_VALE
  - SPELL_LYCHEE
  - JSON_V8R
  - YAML_V8R
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - SPELL_LYCHEE
  - YAML_YAMLLINT
  - MARKDOWN_FMLINT

# === RegEx Excludes ===
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
COPYPASTE_FILTER_REGEX_EXCLUDE: '(pproxy)/.*'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)

# === Spelling ===
SPELL_CSPELL_FILE_EXTENSIONS: [".md", ".txt"]
SPELL_VALE_FILE_EXTENSIONS:
  - .md

# === Linter Arguments ===
DOCKERFILE_HADOLINT_ARGUMENTS: |
  --ignore DL3003
  --ignore DL3007
  --ignore DL3013
  --ignore DL3016
  --ignore DL3018
  --ignore DL3028
  --ignore DL3059
  --ignore DL4001
  --ignore DL4006
  --ignore SC2015
  --ignore SC2016
  --ignore SC2039
  --ignore SC2086
  --ignore SC1091
  --ignore SC3046
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".automation/test"
  - "--skip-dirs"
  - ".venv"
REPOSITORY_TRUFFLEHOG_ARGUMENTS:
  - --exclude-paths=.trufflehogignore

# === General Configs ===
PRINT_ALL_FILES: false
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false

# === Plugins ===
PLUGINS:
  - https://raw.githubusercontent.com/wesley-dean/mega-linter-plugin-fmlint/refs/heads/main/mega-linter-plugin-fmlint/fmlint.megalinter-descriptor.yml

# === Additional Commands ===
# PRE_COMMANDS:
#   - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
#     cwd: "root"
# POST_COMMANDS:
#   - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
#     cwd: "workspace"
