# ~/.config/1Password/ssh/agent.toml
# This file is managed by Nix (nix-darwin + home-manager)
# Manual changes may be overwritten on system rebuild

# Git signing key for Bespin Project
[[ssh-keys]]
item = "bespin-auth"
vault = "rtx-bespin"
account = "Avengers"

# Git authentication key for Bespin Project
[[ssh-keys]]
item = "bespin-sign"
vault = "rtx-bespin"
account = "Avengers"

# GitLab SSH key (USAF)
[[ssh-keys]]
item = "GitLab"
vault = "USAF"
account = "Avengers"

# Git authentication key for RTX GitLab
[[ssh-keys]]
item = "gitlab-auth"
vault = "Raytheon"
account = "Avengers"

# SANS SEC488 course SSH key
[[ssh-keys]]
item = "SEC488"
vault = "SANS"
account = "Avengers"

# Additional SSH keys to be configured:
# - GitHub personal account
# - Homelab infrastructure
# - Kit.xyz services
# - A Cloud Guru platform
# - Elastic Cloud
# - OffSec labs
