# ~/.config/1Password/ssh/agent.toml
# This file is managed by Nix (nix-darwin + home-manager)
# Manual changes may be overwritten on system rebuild

# cfs(bespin):sign
[[ssh-keys]]
item = "vipoogikkiwhupg62nolhh3s6y"

# cfs(bespin):auth
[[ssh-keys]]
item = "7wrp2wy6re2rtf262h7iyjezuy"

# 51nos
[[ssh-keys]]
item = "3f33pkgx4r3atsdjpdyg37nwru"

# cfs
[[ssh-keys]]
item = "pf7qqkab7nz7ufmhvjirtuf6be"

# cfs(gitlab):auth
[[ssh-keys]]
item = "qycn2mtcodebjidrqin5k7q5hy"

# github
[[ssh-keys]]
item = "qagqzim6dvtbopwnwhtyk6zjje"

# cisco(github):auth
[[ssh-keys]]
item = "fkkv2ntnwxdz3pmbx5nd6tnqgy"

# cisco(ite)
[[ssh-keys]]
item = "fkkv2ntnwxdz3pmbx5nd6tnqgy"

# cisco(il5)
[[ssh-keys]]
item = "eztnkttd546q64o3e6rnqb4tcq"

# cisco(il6)
[[ssh-keys]]
item = "akn3gslikqn2py6xki5ncxi254"

# cisco(combine)
[[ssh-keys]]
item = "uvp6h52e767ptady4m573oeyl4"

# vm(nixos)
[[ssh-keys]]
item = "kc74enlgu5vee374cqox4bmiai"

# Additional SSH keys to be configured:
# - GitHub personal account
# - Homelab infrastructure
# - Kit.xyz services
# - A Cloud Guru platform
# - Elastic Cloud
# - OffSec labs
