# ~/.config/1Password/ssh/agent.toml
# This file is managed by Nix (nix-darwin + home-manager)
# Manual changes may be overwritten on system rebuild

# Git signing key for Bespin Project
[[ssh-keys]]
item = "7wrp2wy6re2rtf262h7iyjezuy"

# Git authentication key for Bespin Project
[[ssh-keys]]
item = "vipoogikkiwhupg62nolhh3s6y"

# GitLab SSH key (USAF)
[[ssh-keys]]
item = "3f33pkgx4r3atsdjpdyg37nwru"

# Git authentication key for RTX GitLab
[[ssh-keys]]
item = "qycn2mtcodebjidrqin5k7q5hy"

[[ssh-keys]]
item = "fkkv2ntnwxdz3pmbx5nd6tnqgy"

# SANS SEC488 course SSH key
[[ssh-keys]]
item = "es3f7nrfsyozjzdjfmejficihu"
