set shell := ["bash", "-euo", "pipefail", "-c"]

import '../.build/just/lib.just'

dotdir := shell("yq '.dotdir' data.yml | envsubst")

install: config

config:
    ln -sf "{{justfile_directory()}}/.bashrc" "{{dotdir}}/.bashrc"
